sudo: required
services:
  - docker

before_install:
  - docker build -t tistol/docker-react -f Dockerfile.dev .

script:
 - docker run tistol/docker-react npm run test -- --coverage

 deploy:
  provider: elasticbeantalk
  region: "us-east-2"
  app: "Demo"
  env: "Demo-env"
  bucket_name: "elasticbeanstalk-us-east-2-090070198382"
  bucket_path: "Demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY