on:
  push:
    branches:
      - master

env:
  AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Checkout
  #       run: docker build -t tistol/docker-react -f Dockerfile.dev .
        
  #     - name: Tests
  #       run: docker run tistol/docker-react npm run test -- --coverage
  

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Build
        run: docker build -t tistol/docker-react -f Dockerfile .
      - name: Generate Deployment Package
        run: zip -r deploy.zip *
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
          
      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: "AKIARJ6E2FBXM5TYNJOR"
          aws_secret_key: "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"
          application_name: "Demo"
          environment_name: "Demo-env"
          version_label: "Demo-${{ steps.format-time.outputs.replaced }}"
          region: "us-east-1"
          deployment_package: deploy.zip


  # deploy:
  #     name: Deploy
  #     runs-on: ubuntu-latest
  #     environment: production
  #     steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
  #       with:
  #         aws-access_key_id: $AWS_ACCESS_KEY
  #         aws-secret-access_key: $AWS_SECRET_KEY
  #         aws-region: "us-east-2"
      
  #       provider: elasticbeantalk
  #       app: "Demo"
  #       env: "Demo-env"
  #       bucket_name: "elasticbeanstalk-us-east-2-090070198382"
  #       bucket_path: "Demo"
  #       on:
  #         branch: master